from wand.image import Image
import re
import math
import os

os.chdir('icons')
ls = os.listdir()

# All folder names (Lua files without extension)
folders = [item[:-4] for item in ls if item.endswith(".lua")]

os.makedirs('compiled', exist_ok=True)

# Step 1: Find all image paths per folder in all Lua files
images_per_folder = {folder: set() for folder in folders}
for folder in folders:
    regex = rf's\[.*?\].*?=(?!.*?{{).*?"LibCustomIcons/icons/{folder}/([^"]+)"'
    for cFolder in folders:
        lua_path = f"{cFolder}.lua"
        with open(lua_path, "r", encoding="utf-8") as fil:
            content = fil.read()
            found = re.findall(regex, content)
            images_per_folder[folder].update(found)

# Step 2: Group globally by image size
size_groups = {}  # (w,h) -> list of (folder, imageName)
for folder, images in images_per_folder.items():
    for imageName in images:
        img_path = f"{folder}/{imageName}"
        if not os.path.exists(img_path):
            print(f"Warning: {img_path} missing, skipped")
            continue
        try:
            with Image(filename=img_path) as im:
                wh = (im.width, im.height)
            size_groups.setdefault(wh, []).append((folder, imageName))
        except Exception as e:
            print(f"Error loading {img_path}: {e}")

# Step 3: Generate an atlas per size
coord_map = {}  # (folder,imageName) -> (w,h,left,right,top,bottom,total_w,total_h)
for (w, h), entries in size_groups.items():
    count = len(entries)
    if count == 0:
        continue
    columns = max(1, math.floor(math.sqrt(count)))
    rows = math.ceil(count / columns)
    total_w = columns * w - 1
    total_h = rows * h - 1
    print(f"Creating global atlas {w}x{h}: {columns}x{rows} (images: {count})")

    with Image(background=None) as atlas:
        for i, (folder, imageName) in enumerate(entries):
            img_path = f"{folder}/{imageName}"
            try:
                with Image(filename=img_path) as item:
                    item.border_color = 'none'
                    item.matte_color = 'none'
                    item.background_color = 'none'
                    atlas.image_add(item)
            except Exception as e:
                print(f"Error adding {img_path}: {e}")
        atlas.background_color = "none"
        atlas.montage(mode='concatenate', tile=f'{columns}x{rows}')
        atlas.compression = "dxt5"
        atlas.background_color = "none"
        atlas.format = "dds"
        out_name = f'compiled/merged_{w}x{h}.dds'
        atlas.save(filename=out_name)

    # Calculate coordinates
    for i, (folder, imageName) in enumerate(entries):
        column = i % columns
        row = i // columns
        left = column * w
        right = left + w - 1
        top = row * h
        bottom = top + h - 1
        coord_map[(folder, imageName)] = (w, h, left, right, top, bottom, total_w, total_h)

# Step 4: Collect every s[" line (replace if atlas match) into compiled/static.lua
output_path = 'compiled/static.lua'
lines_out = []

for cFolder in folders:
    lua_path = f"{cFolder}.lua"
    with open(lua_path, "r", encoding="utf-8") as fil:
        for raw_line in fil:
            line_no_nl = raw_line.rstrip('\n')
            stripped = line_no_nl.lstrip()
            # Only lines that start with s[" - these are static icon definitions
            if not stripped.startswith('s["'):
                continue

            replaced_line = None
            for (folder, imageName), (w, h, left, right, top, bottom, total_w, total_h) in coord_map.items():
                needle = f'"LibCustomIcons/icons/{folder}/{imageName}"'
                if needle not in line_no_nl:
                    continue
                regex = rf'(s\[.*?\].*?=)(?!.*?{{).*?"LibCustomIcons/icons/{folder}/{re.escape(imageName)}"'
                m = re.search(regex, line_no_nl)
                if not m:
                    continue
                prefix = m.group(1).rstrip()
                replaced_line = f'{prefix} {{"LibCustomIcons/icons/compiled/merged_{w}x{h}.dds", {left}, {right}, {top}, {bottom}, {total_w}, {total_h}}} -- {folder}/{imageName}'
                break  # Erste passende Ersetzung reicht

            lines_out.append(replaced_line if replaced_line else line_no_nl)

with open(output_path, 'w', encoding='utf-8') as out:
    out.write('-- SPDX-FileCopyrightText: 2025 m00nyONE\n')
    out.write('-- SPDX-License-Identifier: Artistic-2.0\n\n')
    out.write('-- auto generated by compile script --\n\n')
    out.write('local lib_name = "LibCustomIcons"\n')
    out.write('local lib = _G[lib_name]\n')
    out.write('local s = lib.GetStaticTable()\n')
    out.write('local a = lib.GetAnimatedTable()\n\n')
    for l in lines_out:
        out.write(l + '\n')

print(f"Done. Wrote {len(lines_out)} lines to {output_path}.")
