-- SPDX-FileCopyrightText: 2026 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0
local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@RedBoul"] = "LibCustomIcons/icons/misc8/RedBoul.dds"
s["@Soul_Hagans"] = "LibCustomIcons/icons/misc8/Soul_Hagans.dds"
s["@Ukmadorian"] = "LibCustomIcons/icons/misc8/Ukmadorian.dds"
a["@Kuroko29012"] = {"LibCustomIcons/icons/misc8/Kuroko29012_anim.dds", 17, 1, 10}
s["@Chio-Cill"] = "LibCustomIcons/icons/misc8/Chio_Cill.dds"
s["@NecroCat_Crimson"] = "LibCustomIcons/icons/misc8/NecroCat_Crimson.dds"
s["@zDarkus"] = "LibCustomIcons/icons/misc8/zDarkus.dds"
a["@Juanut0"] = {"LibCustomIcons/icons/misc8/Juanut0_anim.dds", 7, 5, 12}
a["@krdntro"] = {"LibCustomIcons/icons/misc8/krdntro_anim.dds", 9, 1, 13}
a["@AsieRubio"] = {"LibCustomIcons/icons/misc8/AsieRubio_anim.dds", 7, 5, 12}
a["@itsTraka"] = {"LibCustomIcons/icons/misc8/itsTraka_anim.dds", 7, 5, 12}
a["@IBelmonteI"] = {"LibCustomIcons/icons/misc8/ibelmontei_anim.dds", 16, 1, 16}
s["@Beaver720"] = "LibCustomIcons/icons/misc8/Beaver720.dds"
a["@Beaver720"] = {"LibCustomIcons/icons/misc8/Beaver720_anim.dds", 10, 5, 25}
s["@Freddingerz"] = "LibCustomIcons/icons/misc8/Freddingerz.dds"
s["@Senfkorn"] = "LibCustomIcons/icons/misc8/Senfkorn.dds"
a["@ClothFollow1"] = {"LibCustomIcons/icons/misc8/ClothFollow1_anim.dds", 6, 6, 25}
a["@Paaatchy"] = {"LibCustomIcons/icons/misc8/Paaatchy_anim.dds", 6, 6, 12}
a["@DeadHistory"] = {"LibCustomIcons/icons/misc8/DeadHistory_anim.dds", 43, 1, 20}
s["@NierielSootica"] = "LibCustomIcons/icons/misc8/NierielSootica.dds"
a["@EviceratorN"] = {"LibCustomIcons/icons/misc8/EviceratorN_anim.dds", 12, 4, 20}
a["@MatejSitar"] = {"LibCustomIcons/icons/misc8/MatejSitar_anim.dds", 12, 1, 25}
s["@Admral_Snakbar"] = "LibCustomIcons/icons/misc8/Admral_Snakbar.dds"
s["@Akira_tm"] = "LibCustomIcons/icons/misc8/Akira_tm.dds"
a["@Nicotine92"] = {"LibCustomIcons/icons/misc8/Nicotine92_anim.dds", 10, 5, 10}
s["@MrSalv"] = "LibCustomIcons/icons/misc8/MrSalv.dds"
s["@Arhwan"] = "LibCustomIcons/icons/misc8/Arhwan.dds"
s["@Wusband"] = "LibCustomIcons/icons/misc8/Wusband.dds"
a["@Wusband"] = {"LibCustomIcons/icons/misc8/Wusband_anim.dds", 6, 1, 10}
s["@LilianHeart"] = "LibCustomIcons/icons/misc8/LilianHeart.dds"
s["@Velarion"] = "LibCustomIcons/icons/misc8/Velarion.dds"
s["@vladossk"] = "LibCustomIcons/icons/misc8/vladossk.dds"
s["@Valerachich"] = "LibCustomIcons/icons/misc8/Valerachich.dds"
s["@Witcher988"] = "LibCustomIcons/icons/misc8/Witcher988.dds"
s["@gnomeimnot"] = "LibCustomIcons/icons/misc8/gnomeimnot.dds"
a["@TrustInDust"] = {"LibCustomIcons/icons/misc8/TrustInDust_anim.dds", 23, 2, 23}
s["@Fanatir"] = "LibCustomIcons/icons/misc8/Fanatir.dds"
s["@kantal1st"] = "LibCustomIcons/icons/misc8/kantal1st.dds"
a["@Barrrny"] = {"LibCustomIcons/icons/misc8/barrrny_anim.dds", 69, 1, 20}
s["@Barrrny"] = "LibCustomIcons/icons/misc8/barrrny.dds"
a["@Nickx9"] = {"LibCustomIcons/icons/misc8/Nickx9_anim.dds", 11, 1, 4}
a["@LeeWangcai"] = {"LibCustomIcons/icons/misc8/LeeWangcai_anim.dds", 15, 2, 8}
a["@Saarz"] = {"LibCustomIcons/icons/misc8/Saarz_anim.dds", 16, 1, 9}
a["@ShuguBota"] = {"LibCustomIcons/icons/misc8/ShuguBota_anim.dds", 20, 1, 25}
a["@FIatIining"] = {"LibCustomIcons/icons/misc8/FIatIining_anim.dds", 45, 1, 30}
s["@PyroFD3S"] = "LibCustomIcons/icons/misc8/PyroFD3S.dds"
s["@rowenlacour"] = "LibCustomIcons/icons/misc8/rowenlacour.dds"
s["@CJACKS25"] = "LibCustomIcons/icons/misc8/CJACKS25.dds"
s["@TABANTHAA"] = "LibCustomIcons/icons/misc8/TABANTHAA.dds"
s["@mdjessup"] = "LibCustomIcons/icons/misc8/mdjessup.dds"
s["@NicoleScarlet"] = "LibCustomIcons/icons/misc8/NicoleScarlet.dds"
s["@DunklesLink"] = "LibCustomIcons/icons/misc8/DunklesLink.dds"
a["@Sher-E"] = {"LibCustomIcons/icons/misc8/Sher-E_anim.dds", 17, 2, 12.5}
a["@BEAR_406ttv"] = {"LibCustomIcons/icons/misc8/BEAR_406ttv_anim.dds", 10, 1, 10}
s["@LuttyTheKiller"] = "LibCustomIcons/icons/misc8/LuttyTheKiller.dds"
s["@Hanadila"] = "LibCustomIcons/icons/misc8/Hanadila.dds"
a["@Hanadila"] = {"LibCustomIcons/icons/misc8/Hanadila_anim.dds", 10, 5, 20}
a["@SomebodyNobody"] = {"LibCustomIcons/icons/misc8/SomebodyNobody_anim.dds", 19, 1, 12.5}
a["@Jirachi_Ex"] = {"LibCustomIcons/icons/misc8/Jirachi_Ex_anim.dds", 10, 1, 5}
s["@DestroyerESO"] = "LibCustomIcons/icons/misc8/DestroyerESO.dds"
s["@LordG.36"] = "LibCustomIcons/icons/misc8/LordG36.dds"
-- a["@LordG.36"] = {"LibCustomIcons/icons/misc8/LordG36_anim.dds", 0, 0, 0}
s["@Clutter_Monk"] = "LibCustomIcons/icons/misc8/Clutter_Monk.dds"
s["@RodMajors"] = "LibCustomIcons/icons/misc8/RodMajors.dds"
s["@dye_qwerty"] = "LibCustomIcons/icons/misc8/dye_qwerty.dds"
s["@Xphalt"] = "LibCustomIcons/icons/misc8/Xphalt.dds"
s["@SkinnyBE"] = "LibCustomIcons/icons/misc8/SkinnyBE.dds"
s["@paradiys"] = "LibCustomIcons/icons/misc8/paradiys.dds"
a["@Kaioshin14"] = {"LibCustomIcons/icons/misc8/Kaioshin14_anim.dds", 9, 1, 10}
s["@CheshireNeko"] = "LibCustomIcons/icons/misc8/CheshireNeko.dds"
a["@SLIMLAC2000"] = {"LibCustomIcons/icons/misc8/SLIMLAC2000_anim.dds", 11, 4, 33}
s["@Cheesecattac"] = "LibCustomIcons/icons/misc8/Cheesecattac.dds"
s["@Taku3mi"] = "LibCustomIcons/icons/misc8/Taku3mi.dds"
s["@SnowPrime"] = "LibCustomIcons/icons/misc8/SnowPrime.dds"
s["@xkuroibara"] = "LibCustomIcons/icons/misc8/xkuroibara.dds"